### PR TITLE
Adding a scale option

### PR DESCRIPTION
**Pull request by HunorMarton**
The scale option can resize the SVG. By default it is 1

- Mentioned in README
- Tests still run
- Seems to work with both Scratch 2 and 3 style

Two things I'm not sure of 
- What is the `client.js` file and if it should be modified 
- Did it / should it affect the image export features?

```js
scratchblocks.renderMatching('pre.blocks', {
  style:     'scratch3',   // Optional, defaults to 'scratch2'.
  languages: ['en', 'de'], // Optional, defaults to ['en'].
  scale: 1,                // Optional, defaults to 1
});
```

### CODE REVIEW

File: index.html [hunk 1]
```diff
@@ -216,9 +213,11 @@ <h1>
   console.log(scratchblocks.stringify(doc));
   var docView3 = scratchblocks.newView(doc, {
     style: "scratch3",
+    scale: 0.675
```
Comment (tjvr) [inline index.html:216]: Neat!

File: snapshots/client.js [hunk 2]
```diff
@@ -11,6 +11,7 @@ window.render = function(source, options, scale) {
 
   var view = scratchblocks.newView(doc, {
     style: options.style,
+    scale: options.scale
```
Comment (tjvr) [inline snapshots/client.js:14]: This looks fine!

The `client.js` file is just used for rendering the snapshots, which are a half-baked attempt at snapshot tests. They’re sometimes useful for checking I haven’t broken anything!

File: scratch2/draw.js [hunk 3]
```diff
@@ -59,11 +59,11 @@ var SVG = (module.exports = {
...
 
-  newSVG(width, height) {
+  newSVG(width, height, scale) {
     return SVG.el("svg", {
       version: "1.1",
-      width: width,
-      height: height,
+      width: width * scale,
+      height: height * scale,
       viewBox: `0 0 ${width} ${height}`,
```
Comment (tjvr) [inline scratch2/draw.js:67]: I think this is right, but do you happen to know of any documentation confirming that we can scale an SVG by setting the width/height and the `viewBox` to different values?

I’m just wondering if we should be setting them to the same thing, and then using an explicit `transform()` instead.

**Review by tjvr — COMMENTED** [review]
This looks great to me, thanks for sending it!

I don’t think I have any requests for changes; I’d just like to find some time to test this out before I merge it!

The question about exports is an interesting one. I’m not sure what result I’d expect; probably I’d expect the PNG to be exported at the scaled resolution. Which is presumably what happens!

File: index.html (hunk 1 above)
Comment (HunorMarton) [reply index.html:216]: Actually this is the reason for this PR, because even Scratch itself is scaled.

File: scratch2/draw.js (hunk 3 above)
Comment (HunorMarton) [reply scratch2/draw.js:67]: In my understanding the two things are independent. I like to think of width and height as the "external" size of the image from the perspective of the website and viewBox as the "internal" size from the perspective of the image elements.

MDN doesn't indicate that they should be tied together (https://developer.mozilla.org/en-US/docs/Web/SVG/Element/svg), and it would be redundant if that would be the case.

**Comment by tjvr** [comment]
Thanks so much for sending this! Turned out we did need to update the image export feature, so I've gone ahead and done that :ok_hand:

**Comment by alexwenbj** [comment]
I don't know wether it is this PR broke something, I compiled the latest repo and use exportSVG(), it showed me an error :`scratchblocks.min.js:9 Error: <svg> attribute height: Expected length, "NaN".`, but it is OK when I use the latest stable download version 3.5.2 。

**Comment by tjvr** [comment]
I suspect that's caused by #384!

**Comment by alexwenbj** [comment]
@tjvr Thank you.
